language: ruby
sudo: required
dist: trusty
cache:
- bundler
install:
- bundle install
rvm:
- 1.9.3
- 2.0
- 2.1
- 2.2
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-postfix.gemspec
- gem install sensu-plugins-postfix-*.gem
- bundle exec kitchen test
env:
- KITCHEN_LOCAL_YAML=.kitchen.travis.yml
deploy:
  provider: rubygems
  api_key:
    secure: LkxKFc6KYmwTfuwIhFWSktky5TiJMvI79+RpHaX3BUyEnqZMAVNxtmTXpWqqglXGjgEGeClYl1WMCXIamw2zeLlK6CEuBJXcVXs4O27UKkvfzVmiDYBITPtF02mTVCTYd5NNch67Rh5rT7wTN2hxWbiE2OFw6/WIF9hD2mr1484=
  gem: sensu-plugins-postfix
  on:
    ags: true
    all_branches: true
    rvm: 1.9.3
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    repo: sensu-plugins/sensu-plugins-postfix
